### ISSUE TITLE
easy: Filter out lines that start with ``` in output in discord bot

### ISSUE THREAD

**Issue by luciusmagn** [Testausserveri/testauskameli#10]
It is easy to mess up the resulting formatting if you are Mixu and try printing \``` everywhere. To maintain handsomeness, the discord bot should filter out lines that start with \``` (in other places, it is meaningless)

This change needs to be done here:
https://github.com/Testausserveri/testauskameli/blob/3ad1f5c9716bdf5c9e1fa977d593cc255665906a/bot/src/executor.rs#L45-L80

And it concerns the bindings `output` and `error` in respective match arms.

Cookbook:
- For each mach block, add a `let output` and optionally `let error` which will contain the filtered text
- This variable will shadow the original one, so no further changes should be necessary

Tips:
- Iterators over strings and chars can collect into strings
- you can use the [str::lines()](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.lines) iterator on String to get lines
- then you can use the `filter` method to filter out undesirable lines, and subsequently collect into a String

**Comment by Chicken** [comment]
Instead of filtering the lines one could just replace all instances of ``` with \\\`\\\`\\\`

**Comment by luciusmagn** [comment]
That is also true

**Comment by luciusmagn** [comment]
You can implement it, if you want, @Chicken

**Comment by Chicken** [comment]
![pepeno](https://user-images.githubusercontent.com/45627874/159671518-09ff1c49-62cc-4905-b5bc-6533f476a94d.png)
